{"name": "TC004 - Login with Invalid Credentials", "status": "passed", "description": "\n**Test Scenario:**  \nAttempt to log in using an invalid credentials  \nUsername: Ohitr\nPassword: 9902@KM\n\n**Expected Result:**  \nUser should not be able to log in.\n\n**How it is evaluated:**  \nThe login is considered failed if a snackbar displays the message **Login failed: Invalid credentials**.\n", "steps": [{"name": "Login Page is Opened", "status": "passed", "start": 1750139027073, "stop": 1750139029411}, {"name": "Entering invalid email", "status": "passed", "start": 1750139029411, "stop": 1750139033100}, {"name": "Entering the invalid password", "status": "passed", "start": 1750139033100, "stop": 1750139033599}, {"name": "Clicking the Login button", "status": "passed", "start": 1750139033599, "stop": 1750139033990}, {"name": "Validating error message for failed login", "status": "passed", "attachments": [{"name": "Login failed", "source": "fa736e0c-94b4-4e6f-8761-b8601301a4ca-attachment.txt", "type": "text/plain"}], "start": 1750139033990, "stop": 1750139034562}], "parameters": [{"name": "setup", "value": "'edge'"}], "start": 1750139027073, "stop": 1750139034563, "uuid": "b2799689-9424-4adc-b232-b212d916e301", "historyId": "8785abd94e2f36beb2df8c453130064d", "testCaseId": "df66409949c786e429fa62b97ff2cb96", "fullName": "Xeed_Login_Page.Test_TC004#test_site", "labels": [{"name": "feature", "value": "XEED_Ventures_Login_Page"}, {"name": "parentSuite", "value": "Xeed_Login_Page"}, {"name": "suite", "value": "Test_TC004"}, {"name": "host", "value": "DESKTOP-0Q1NQ4H"}, {"name": "thread", "value": "14904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Xeed_Login_Page.Test_TC004"}]}